name: gpa_calculator
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_svg: ^0.23.0+1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  percent_indicator: ^3.4.0
  flutter_slidable: ^1.1.0
  file_picker: ^4.2.4
  permission_handler: ^8.3.0
  fluttertoast: ^8.0.8
  easy_localization: ^3.0.0
  share: ^2.0.4
  package_info_plus: ^1.3.0
  desktop_window: ^0.4.0
  flutter_dialogs: ^2.1.1
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.0.9
  showcaseview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  hive_generator: ^1.1.1
  flutter_native_splash: ^1.3.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-SemiBold.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/launcher_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "assets/icons/app_icon_background.png"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#002154"
  image: assets/icons/splash.png
  android: true
  ios: true